#
# Load useful libraries
#
import pandas as pd

#
# Define basic interval information
#
list_intervals = [
    {
        'interval name': 'Perfect Unison',
        'interval type': 'Perfect',
        'interval number (string)': 'Unison',
        'interval number (string short)': '1st',
        'interval number (integer)': 1,
        'interval abbreviation': 'P1',
        'chromatic semitone distance': 0,
    },
    {
        'interval name': 'Diminished Second',
        'interval type': 'Diminished',
        'interval number (string)': 'Second',
        'interval number (string short)': '2nd',
        'interval number (integer)': 2,
        'interval abbreviation': 'd2',
        'chromatic semitone distance': 0,
    },
    {
        'interval name': 'Minor Second',
        'interval type': 'Minor',
        'interval number (string)': 'Second',
        'interval number (string short)': '2nd',
        'interval number (integer)': 2,
        'interval abbreviation': 'm2',
        'chromatic semitone distance': 1,
    },
    {
        'interval name': 'Augmented Unison',
        'interval type': 'Augmented',
        'interval number (string)': 'Unison',
        'interval number (string short)': '1st',
        'interval number (integer)': 1,
        'interval abbreviation': 'A1',
        'chromatic semitone distance': 1,
    },
    {
        'interval name': 'Major Second',
        'interval type': 'Major',
        'interval number (string)': 'Second',
        'interval number (string short)': '2nd',
        'interval number (integer)': 2,
        'interval abbreviation': 'M2',
        'chromatic semitone distance': 2,
    },
    {
        'interval name': 'Diminished Third',
        'interval type': 'Diminished',
        'interval number (string)': 'Third',
        'interval number (string short)': '3rd',
        'interval number (integer)': 3,
        'interval abbreviation': 'd3',
        'chromatic semitone distance': 2,
    },
    {
        'interval name': 'Minor Third',
        'interval type': 'Minor',
        'interval number (string)': 'Third',
        'interval number (string short)': '3rd',
        'interval number (integer)': 3,
        'interval abbreviation': 'm3',
        'chromatic semitone distance': 3,
    },
    {
        'interval name': 'Augmented Second',
        'interval type': 'Augmented',
        'interval number (string)': 'Second',
        'interval number (string short)': '2nd',
        'interval number (integer)': 2,
        'interval abbreviation': 'A2',
        'chromatic semitone distance': 3,
    },
    {
        'interval name': 'Major Third',
        'interval type': 'Major',
        'interval number (string)': 'Third',
        'interval number (string short)': '3rd',
        'interval number (integer)': 3,
        'interval abbreviation': 'M3',
        'chromatic semitone distance': 4,
    },
    {
        'interval name': 'Diminished Fourth',
        'interval type': 'Diminished',
        'interval number (string)': 'Fourth',
        'interval number (string short)': '4th',
        'interval number (integer)': 4,
        'interval abbreviation': 'd4',
        'chromatic semitone distance': 4,
    },
    {
        'interval name': 'Perfect Fourth',
        'interval type': 'Perfect',
        'interval number (string)': 'Fourth',
        'interval number (string short)': '4th',
        'interval number (integer)': 4,
        'interval abbreviation': 'P4',
        'chromatic semitone distance': 5,
    },
    {
        'interval name': 'Augmented Third',
        'interval type': 'Augmented',
        'interval number (string)': 'Third',
        'interval number (string short)': '3rd',
        'interval number (integer)': 3,
        'interval abbreviation': 'A3',
        'chromatic semitone distance': 5,
    },
    {
        'interval name': 'Diminished Fifth',
        'interval type': 'Diminished',
        'interval number (string)': 'Fifth',
        'interval number (string short)': '5th',
        'interval number (integer)': 5,
        'interval abbreviation': 'd5',
        'chromatic semitone distance': 6,
    },
    {
        'interval name': 'Augmented Fourth',
        'interval type': 'Augmented',
        'interval number (string)': 'Fourth',
        'interval number (string short)': '4th',
        'interval number (integer)': 4,
        'interval abbreviation': 'A4',
        'chromatic semitone distance': 6,
    },
    {
        'interval name': 'Perfect Fifth',
        'interval type': 'Perfect',
        'interval number (string)': 'Fifth',
        'interval number (string short)': '5th',
        'interval number (integer)': 5,
        'interval abbreviation': 'P5',
        'chromatic semitone distance': 7,
    },
    {
        'interval name': 'Diminished Sixth',
        'interval type': 'Diminished',
        'interval number (string)': 'Sixth',
        'interval number (string short)': '6th',
        'interval number (integer)': 6,
        'interval abbreviation': 'd6',
        'chromatic semitone distance': 7,
    },
    {
        'interval name': 'Minor Sixth',
        'interval type': 'Minor',
        'interval number (string)': 'Sixth',
        'interval number (string short)': '6th',
        'interval number (integer)': 6,
        'interval abbreviation': 'm6',
        'chromatic semitone distance': 8,
    },
    {
        'interval name': 'Augmented Fifth',
        'interval type': 'Augmented',
        'interval number (string)': 'Fifth',
        'interval number (string short)': '5th',
        'interval number (integer)': 5,
        'interval abbreviation': 'A5',
        'chromatic semitone distance': 8,
    },
    {
        'interval name': 'Major Sixth',
        'interval type': 'Major',
        'interval number (string)': 'Sixth',
        'interval number (string short)': '6th',
        'interval number (integer)': 6,
        'interval abbreviation': 'M6',
        'chromatic semitone distance': 9,
    },
    {
        'interval name': 'Diminished Seventh',
        'interval type': 'Diminished',
        'interval number (string)': 'Seventh',
        'interval number (string short)': '7th',
        'interval number (integer)': 7,
        'interval abbreviation': 'd7',
        'chromatic semitone distance': 9,
    },
    {
        'interval name': 'Minor Seventh',
        'interval type': 'Minor',
        'interval number (string)': 'Seventh',
        'interval number (string short)': '7th',
        'interval number (integer)': 7,
        'interval abbreviation': 'm7',
        'chromatic semitone distance': 10,
    },
    {
        'interval name': 'Augmented Sixth',
        'interval type': 'Augmented',
        'interval number (string)': 'Sixth',
        'interval number (string short)': '6th',
        'interval number (integer)': 6,
        'interval abbreviation': 'A6',
        'chromatic semitone distance': 10,
    },
    {
        'interval name': 'Major Seventh',
        'interval type': 'Major',
        'interval number (string)': 'Seventh',
        'interval number (string short)': '7th',
        'interval number (integer)': 7,
        'interval abbreviation': 'M7',
        'chromatic semitone distance': 11,
    },
    {
        'interval name': 'Diminished Octave',
        'interval type': 'Diminished',
        'interval number (string)': 'Octave',
        'interval number (string short)': '8th',
        'interval number (integer)': 8,
        'interval abbreviation': 'd8',
        'chromatic semitone distance': 11,
    },
    {
        'interval name': 'Perfect Octave',
        'interval type': 'Perfect',
        'interval number (string)': 'Octave',
        'interval number (string short)': '8th',
        'interval number (integer)': 8,
        'interval abbreviation': 'P8',
        'chromatic semitone distance': 12,
    },
    {
        'interval name': 'Augmented Seventh',
        'interval type': 'Augmented',
        'interval number (string)': 'Seventh',
        'interval number (string short)': '7th',
        'interval number (integer)': 7,
        'interval abbreviation': 'A7',
        'chromatic semitone distance': 12,
    },
]

#
# Create a DataFrame version of the intervals list
#
df_intervals = pd.DataFrame(list_intervals)

#
# Test at command line
#
if __name__ == '__main__':
    print(df_intervals)
